@SETLOCAL
@IF NOT DEFINED NODE_PATH (
  @SET "NODE_PATH=C:\Users\Administrator\Documents\GitHub\sinpomarket\node_modules\.pnpm\@astrojs+check@0.9.10_prettier@3.9.6_typescript@6.0.3\node_modules\@astrojs\check\node_modules;C:\Users\Administrator\Documents\GitHub\sinpomarket\node_modules\.pnpm\@astrojs+check@0.9.10_prettier@3.9.6_typescript@6.0.3\node_modules;C:\Users\Administrator\Documents\GitHub\sinpomarket\node_modules\.pnpm\node_modules"
) ELSE (
  @SET "NODE_PATH=C:\Users\Administrator\Documents\GitHub\sinpomarket\node_modules\.pnpm\@astrojs+check@0.9.10_prettier@3.9.6_typescript@6.0.3\node_modules\@astrojs\check\node_modules;C:\Users\Administrator\Documents\GitHub\sinpomarket\node_modules\.pnpm\@astrojs+check@0.9.10_prettier@3.9.6_typescript@6.0.3\node_modules;C:\Users\Administrator\Documents\GitHub\sinpomarket\node_modules\.pnpm\node_modules;%NODE_PATH%"
)
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\..\@astrojs\check\bin\astro-check.js" %*
) ELSE (
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\..\@astrojs\check\bin\astro-check.js" %*
)
