@SETLOCAL
@IF NOT DEFINED NODE_PATH (
  @SET "NODE_PATH=C:\Users\Administrator\Documents\GitHub\sinpomarket\node_modules\.pnpm\wrangler@4.125.0\node_modules\wrangler\node_modules;C:\Users\Administrator\Documents\GitHub\sinpomarket\node_modules\.pnpm\wrangler@4.125.0\node_modules;C:\Users\Administrator\Documents\GitHub\sinpomarket\node_modules\.pnpm\node_modules"
) ELSE (
  @SET "NODE_PATH=C:\Users\Administrator\Documents\GitHub\sinpomarket\node_modules\.pnpm\wrangler@4.125.0\node_modules\wrangler\node_modules;C:\Users\Administrator\Documents\GitHub\sinpomarket\node_modules\.pnpm\wrangler@4.125.0\node_modules;C:\Users\Administrator\Documents\GitHub\sinpomarket\node_modules\.pnpm\node_modules;%NODE_PATH%"
)
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\..\wrangler\bin\cf-wrangler.js" %*
) ELSE (
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\..\wrangler\bin\cf-wrangler.js" %*
)
